red-gate/RedGate.Build

Public/Sign-Assembly.ps1
Sign-Assembly is a function to sends a compiled assembly to a webserver so that the assembly can be digitally signed.
FYI: @nyctef, @samblackburn, @ChrisLambrou feel free to start using it in your build scripts once this is merged :smile:
=> Sign-Assembly function

Public/Merge-CoverageReports.ps1
Looks like merging the coverage report is causing dotcover.exe to not recognize it when importing it with Teamcity...
=> Merge-CoverageReports: do not zip the merged report

Public/ConvertTo-ShellEscaped.ps1, Public/Install-DotCoverPackage.ps1, Public/Install-NUnitPackage.ps1, Public/Install-Package.ps1, Public/Install-SmartAssemblyPackage.ps1, Public/New-NuGetPackageVersion.ps1, Public/New-TempDir.ps1, Public/Tests/Test-NugetPackagesVersionsAreConsistent.ps1, Tests/PowershellHelp.Tests.ps1, build.ps1
New `Tests/PowershellHelp.Tests.ps`1 is using Pester to check that every function exported by `RedGate.Build` does have a minimal amount of help that is available for end users.
Currently checks for:
* For each function:
* synopsis
* description
* For each parameter:
* description
The test will fail if any function is missing one or more of those...
Also fixed the functions for which the test failed. (did catch a couple of functions where the help was not available / properly parsed by Powershell ) :triumph:
=> Check help

Public/Tests/Test-ScriptForParsingErrors.ps1, Tests/Tests/Test-ScriptForParsingErrors.Tests.ps1
Test-ScriptForParsingErrors can be useful to check the syntax of Invoke-Build scripts before trying to run them and getting obscure `A parameter cannot be found that matches parameter name 'xxx'` messages....
=> new function Test-ScriptForParsingErrors

Public/Invoke-SigningService.ps1
* `Invoke-SigningService` has a new `-HashAlgorithm` parameter:
* can take 2 values. `sha1` and `sha256`. `sha256` is selected by default.
* `Invoke-SigningService` has a new `-Force` parameter:
* can be used to force re-signing files that have already been signed.
=> Ability to sign files using sha256

Public/Invoke-SigningService.ps1, Tests/Invoke-SigningService.Tests.ps1
Force the signing of msi files to use sha256.
Force users to specify which algorithm to use to sign vsix files.
Trust the signing service to have valid defaults for everything else.
+ some tests!
=> Updated Invoke-SigningService to deal with changes to our signing service.

Public/Invoke-SigningService.ps1
...when signing a ClickOnce manifest.
This is currently preventing us from using Redgate.Build to sign our ClickOnce installer.
Tested in that it doesn't crash on my machine.
=> Prevent "Unsupported file type" error

Public/Invoke-NUnitForAssembly.ps1
that will have to do :disappointed_relieved:
=> Do not publish dotcover snapshot file (*.coverage.snap)

.gitignore, Private/_Init.ps1, Public/New-TempDir.ps1, Tests/New-TempDir.Tests.ps1
This is an attempt at speeding up zipping files using New-ZipArchive.
(It turns out that zipping files from %TEMP% is causing our antivirus to interfere and slow things down...)
So create temporary folders in `RedGate.Build\.temp` instead
=> Create temporary folders within the RedGate.Build module folder.

Public/Install-Package.ps1
`Install-Package` now copes with the possibility that NuGet might not install the precise version that was requested. e.g. if version 1.2.3 is asked for, NuGet may actually install version 1.2.3.4.
The solution is to allow NuGet to do it's thing, then scan the packages folder to see what was actually installed, and return the correct folder, rather than guessing the folder based solely on the package id and requested version.
=> Fix Issue 26 - Install-Package copes with version differences

Public/Invoke-DotCoverForExecutable.ps1, Public/Invoke-NUnitForAssembly.ps1
This adds support for dotCover's attribute filters to `Invoke-DotCoverForExecutable` and `Invoke-NUnitForAssembly`.
=> Add support for dotCover attribute filters

Public/Merge-CoverageReports.ps1
While playing with integrating Invoke-NUnitForAssembly with one of our product, I got a few issues and this is a PR to address them...
* Get-ChildItem can fail with `Path is too long` errors. Adding `-ErrorAction SilentlyContinue` swallows those errors. I think the risk of "missing" some snapshot files because of some other error we could now miss is quite low so it's probably all right?
* Renamed `-OutputDir` to `-SnapshotsDir` 
* That's the folder where we're looking for coverage snapshot files.
* Kept `-OutputDir` as an alias of `-SnapshotsDir` for backwards compatibility
* Added `-CoverageOutputDir` that can be set to generate the code coverage in a specific folder.
* If not set, defaults to the value of `-SnapshotsDir`
* Print the Teamcity messages even when this is not being …
=> Merge-CoverageReports improvements

Private/NUnit/Publish-ResultsAndLogsToTeamcity.ps1, Tests/Nunit/2/Invoke-NUnitForAssembly.Tests.ps1
@angellaa This is to fix the breaking change that is breaking your build.
(basically a new private function made `-TestResultFilenamePattern` a required parameter which it wasn't before)
I added a clunky test so that we get to run "Invoke-NUnitForAssembly" when we build `RedGate.Build`. It's ugly but hey this might catch things before we break your world again :blush:
=> Invoke nunit fixes

Public/Read-ReleaseNotes.ps1, Public/Select-ReleaseNotes.ps1, Tests/Read-ReleaseNotes.Tests.ps1, Tests/Select-ReleaseNotes.Tests.ps1
New Select-ReleaseNotes for much more advanced RELEASENOTES.md parsing, also has a strapline accumulator for check for updates releases.
Changed behaviour of Read-ReleaseNotes to fail if the n-part version isn't the first encountered (was seeing issues in some RELEASENOTES finding a much lower version that searched due to incorrect match far down the file)
=> Advanced releasenotes

Public/Select-ReleaseNotes.ps1, Tests/Select-ReleaseNotes.Tests.ps1
Dots weren't allows to try to prevent "100. Rubbish" which github would render as "1. Rubbish" - now force a dash(-) between the priority and the strap line text instead.
=> Allows dots in strap line

Public/New-NuGetPackageVersion.ps1, Public/New-SemanticNuGetPackageVersion.ps1, Tests/New-SemanticNuGetPackageVersion.Tests.ps1
Cmdlet to create a semantically-versioned NuGet package version string.
Supplants New-NuGetPackageVersion.
=> Added New-SemanticNuGetPackageVersion cmdlet

Public/Invoke-DotCoverForExecutable.ps1, Public/Invoke-NUnit3ForAssembly.ps1, Public/Invoke-NUnitForAssembly.ps1, scripts/test-singleassembly.ps1
Add argument so we can pass `/ProcessFilter` argument to dotcover (was added in 2016.2)
Command line reference: https://www.jetbrains.com/help/dotcover/2016.3/dotCover__Console_Runner_Commands.html#cover
We want this to filter out `sqlservr.exe` from our coverage
=> Add Dot Cover Process FIlter Argument

Public/Merge-CoverageReports.ps1
If you run `Invoke-NUnitForAssembly` with a later version of dotcover than `$DefaultDotCoverVersion` then the merge will fail. So allow it to be overridden.
=> Allow dot cover version to be specified when running Merge-CoverReports

Public/Invoke-NUnit3ForAssembly.ps1, Tests/Nunit/3/Invoke-NUnit3ForAssembly.Tests.ps1
Fixes issue with the where condition (used for filtering tests, eg by category) not being passed through as an argument to the NUnit3 command line
=> NUnit3 where condition

Public/Select-ReleaseNotes.ps1, Tests/Select-ReleaseNotes.Tests.ps1
`Select-ReleaseNotes` currently stores each block in the release notes (under a header, e.g. "Features", "Fixes" etc.) indexed as an object property. This is a dictionary, and when release scripts call `GetEnumerator()` on it, the order the blocks is returned is not specified. It appears to be deterministic for a given set of inputs, and returns "General", "Features", "Fixes" in the insertion order, but the addition of another header called "Introduction" messes up the ordering. This means that our release notes were being jumbled up.
This PR makes the `Blocks` property an array of name/value objects rather than an object with properties. As new members are added to the array as the sections are encountered in the release notes, this should mean that the sections are ordered as they first …
=> Return blocks in order from Select-ReleaseNotes

Public/Update-RedgateNugetPackages.ps1
Instead make `-GithubApiToken` optional.
* if `-GithubApiToken` is set, we commit/push changes and create/update a PR
* if `-GithubApiToken` is not set, we do not commit changes
This is going to break any of our build that use `-DoNotCommit` but hey, this should make things simpler?
=> [breaking] Remove -DoNotCommitChanges parameter from Update-RedgateNugetPackages 

Public/Update-RedgateNugetPackages.ps1
This is needed when a package has a x.y.z version but isn't actually semvered, e.g. NUnit
=> Allow user to specify a package version override

Public/Nuget/Update-NuspecDependenciesVersions.ps1, Public/Update-RedgateNugetPackages.ps1
`Update-RedgateNugetPackages` operates in 2 steps: it updates the dependencies of your solution (*.csproj, *.config) and then it updates the .nuspec files to match the changes it just made.
The user can ignore certain packages when doing this, by using `-ExcludedPackages` which will exclude them from the nuget update step.  Unfortunately that didn't exclude them from the nuspec update, and the nuspec update tends to guess a version range by making assumptions about semantic versioning.  
#64 recently provided a workaround, the `-NuspecPackageVersionOverride` switch, which this PR reverts because it exposed the distinction between the 2 steps rather than abstracting it away.
=> Simplify nuget updater API

Public/Update-RedgateNugetPackages.ps1
We want to be able to easily see which packages have been updated in the PR and commit message. This looks at the NuGet output to determine which packages have been updated, and only includes them in any messages. I also changed it so the only things on the Output stream are the modified packages, as we intend to have different behaviour depending on what has been updated.
=> Don't include the packages that have not been updated in the messaging

Private/Nuget/Get-DependencyVersionRange.ps1, Tests/Nuget/Get-DependencyVersionRange.Tests.ps1
This was causing broken nuspec files (eg [this backupreader package](http://nuget.red-gate.com/packages/RedGate.BackupReader/3.1.62-update-shsql-remove-) had a dependency on `RedGate.Shared.SQL (>= 19.0.6-remove-executionbloc && < 20.0.0-remove)`)
I think this got caught by the nuget dependency tests in CompareEngine when we tried to update that package; once we can generate correct packages we can see if this solves the test failures
=> Fix Get-DependencyVersionRange for branches that contain a dash

Private/NUnit/2/Build-NUnitCommandLineArguments.ps1, Tests/Nunit/2/Build-NUnitCommandLineArguments.Tests.ps1
`/xml=` is understood by older versions of nunit 2. `/result=` isn't.
=> Add nunit 2.5.9 support

Public/Nuget/Install-Package.ps1, Public/Nuget/Test-NugetPackage.ps1, Tests/Nuget/Test-NugetPackage.Tests.ps1
Cmdlet used to determine whether or not a specific version of a package exists.
Normally one would use the `nuget.exe list` command, but there's [a long-standing unfixed bug](https://github.com/NuGet/NuGetGallery/issues/3274) that prevents this. This cmdlet provides an alternative method for detecting the presence or absence of a specific package, without having to resort to manually invoking `nuget.exe list`, scraping the output, then realising it's buggy.
The current implementation simply invokes `Install-Package` and then checks to see whether the operation succeeds or fail. Whilst the Pester tests passed, unfortunately this triggered TeamCity build failures because the console error output produced by `nuget.exe` when checking for a non-existent package was interpreted as a sign of a …
=> Added Test-NugetPackage cmdlet

Private/NUnit/3/Build-NUnit3CommandLineArguments.ps1, Public/Invoke-NUnit3ForAssembly.ps1, Tests/Nunit/3/Build-NUnit3CommandLineArguments.Tests.ps1
NUnit3 detects whether it's being executed from Teamcity and does the right thing already.
Removing this will avoid build logs being polluted with Teamcity service messages if we decide to use other CI servers...
Tested and confirmed it is working against a build using NUnit v3.7
=> Remove --teamcity when calling nunit3-console.exe

Private/CIServers.psm1, Private/CIServers/vsts.psm1, RELEASENOTES.md
This PR changes the names of two of the new functions added in https://github.com/red-gate/RedGate.Build/pull/74 to ensure consistency with `TeamCity-SetBuildNumber`
https://github.com/red-gate/RedGate.Build/blob/f059c64e0975a5176f9b62d170b24a150ad76056/Private/CIServers/teamcity.psm1#L154
In particular, the word **Set** in the function name.
=> Consistency with `TeamCity-SetBuildNumber`

Private/NUnit/Publish-ResultsAndLogs.ps1, Public/Invoke-NUnit3ForAssembly.ps1, RELEASENOTES.md
* `Publish-ResultsAndLogs` can now import NUnit results in both Teamcity and VSTS.
* Make sure we do allow `Publish-ResultsAndLogs` to import results when not running from Teamcity.
=> More VSTS / NUnit tweaks

paket.dependencies
Looking at the [Invoke-Build release notes](https://github.com/nightroman/Invoke-Build/blob/v4.0.0/Release-Notes.md#v400), nothing that significant happened at 4.0.0, so we should just upgrade.
(Also, now [my PR to Invoke-Build](https://github.com/nightroman/Invoke-Build/pull/107) is merged, we need to upgrade Invoke-Build for me to benefit from it :smile:)
=> Upgrade Invoke-Build to 4

Public/Merge-CoverageReports.ps1
Always generate dotCover HTML report.
The reason for this change is that SonarQube requires it for proper integration.
=> Always generate dotCover HTML report

Public/Update-RedgateNugetPackages.ps1
This reverts a9dc3d5f2ef which was meant to be a temporary hack <cough>11 months ago<cough> :disappointed:
I would hope everything should work as expected and we're better off excluding that package explicitely when calling `Update-RedgateNugetPackages` (if we really need to) rather than forgetting we've got a special case in here....
=> Do not exclude RedGate.Client.ActivationPluginShim when updating nuget packages

Public/Update-RedgateNugetPackages.ps1
Adds support for new csproj format when updating packages.
Requires being able to run dotnet tools against any csproj using the new `PackageReference` syntax.
This will only run if there is a `PackageReference` so shouldn't affect most tools. I tested it against DLM Automation. Also prevents failure if there are no package configs in the repo
=> Add support for new csproj in update package

Public/GitHub/Get-PullRequest.ps1, Public/GitHub/New-PullRequest.ps1, Public/GitHub/Update-PullRequest.ps1, Tests/Use-Tls.Tests.ps1
The previous PR introduced the `Use-Tls { .... }` function but mangled the return values:
```
Use-Tls {
$result = Invoke-RestMethod ...
}
return $result
```
Unfortunately the result is no longer in scope, so this code always returns null.  In this PR we move the return statement inside the `Use-Tls` block, and add a test to assert that return values will be passed through to the calling method.
=> Fix "PR already exists" errors

Public/Update-RedgateNugetPackages.ps1
In SoC we run the following code:
```
$UpdatePackages = Update-RedgateNugetPackages -Repo 'SQLSourceControl' `
-GithubAPIToken $GithubAPIToken `
-RootDir $RootDir `
-Solution $Solution `
-ExcludedPackages $ExcludedPackages `
-Labels @('needs code review', 'awaiting TC test run', 'needs release notes') `
-UpdateBranchName $UpdateBranch |
Tee-Object -FilePath $OutputDir\nuget-auto-update.log.txt
```
Following recent changes this appears to always return `null`. Since we need this to do further work if `Honeycomb.WPF` is updated this change is a slightly speculative update to restore this behaviour.
=> Write the list of updated packages out

Public/Invoke-SigningService.ps1, RELEASENOTES.md, Tests/Invoke-SigningService.Tests.ps1
**What does this PR do?**
Adds support for calling `Invoke-SigningService` with a NuGet package. The cmdlet then signs any assembly dlls within the `libs` sub-folder of the package.
**Why?**
To date, many build scripts contain the following three separate steps.
1. Compile a solution.
2. Invoke the signing service on specific assembly dlls that were built in step 1.
3. Generate the NuGet packages based on manually maintained `.nuspec` files.
With a gradual move to .NET Standard, .NET Core, the new VS 2017 project format, and multi-platform targeting, steps 1 and 3 are now carried out at the same time by msbuild and the dotnet cli tools. This no longer leaves us with a clean opportunity to sign the assembly dlls after they've been created, but before they've been packaged into a NuGet …
=> Add support to Invoke-SigningService for signing libs in NuGet packages

Public/Invoke-SigningService.ps1, Tests/Invoke-SigningService.Tests.ps1
Addressed an outstanding TODO comment about checking for errors in the signing request. This included:
- Checking the code in the signing service to become convinced that, if the signing fails, an error response is guaranteed.
- Manually testing that the Invoke-WebRequest does indeed raise an error when the signing service returns an error response. Together with the above, this means we're now confident that, when the request succeeds, the response does indeed contain a correctly signed file.
- Explicitly checking the certificate on the returned file. Mainly this guards against a success response, where the response body content was in some way not correctly received in full.
- Saving the response to a temp file, and only overwriting the original input file once we're happy the request …
=> Improved handling of errors in the signing request

Public/Update-ProjectProperties.ps1, RELEASENOTES.md, Tests/Update-ProjectProperties.Tests.ps1
Adds a new `Update-ProjectProperties` cmdlet, that can be used to insert or update the `Version`, `AssemblyVersion`, `FileVersion` and `PackageReleaseNotes` properties within a VS2017-style project file. This is to complement `Update-AssemblyVersion` cmdlet, which does a similar job for `AssemblyInfo.cs` files.
For example, given the following project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
<TargetFramework>netstandard2.0</TargetFramework>
</PropertyGroup>
...etc...
</Project>
```
If you invoke the following:
```powershell
Update-ProjectProperties `
-Version '1.2.3.4-SomeBranch' `
-AssemblyVersion '1.0.0.0' `
-FileVersion '1.2.3.4' `
-PackageReleaseNotes 'RELEASE-NOTES'
```
The project file's contents will be modified as follows:
```xml
<Project …
```
=> New `Update-ProjectProperties` cmdlet

Public/Update-RedgateNugetPackages.ps1
Fix an issue where dotnet output wasn't being printed. Also move it to to verbose stream.
=> Send dotnet output to verbose stream

Public/Invoke-NUnitForAssembly.ps1
Updates `Invoke-NUnitForAssembly` to add `net-4.7` as a supported runtime.
=> Add net-4.7 as a supported framework version.

Public/Select-ReleaseNotes.ps1, RELEASENOTES.md, Tests/Select-ReleaseNotes.Tests.ps1
Leading whitespace can be significant in markdown (it's an indent). Instead of trimming every line in Select-ReleaseNote, modify the relevant Regexs to allow leading whitespace.
I need this so that our auto-uploading release notes in DLMAutomation can have indented sections.
=> Don't trim release notes lines

Private/Nuget/Get-DependencyVersionRange.ps1, Public/Nuget/Update-NuspecDependenciesVersions.ps1, RELEASENOTES.md, Tests/Nuget/Get-DependencyVersionRange.Tests.ps1
With semantic versioning, we generate a range of values when we update a nuspec file. For example, `[1.2.3, 2.0.0)`. This is how strict semantic versioning works.
[Our policy](https://info.red-gate.com/eng/development-policies/libraries/versioning-assemblies) is not a strict interpretation of semantic versioning and as such we sometimes want to enforce a specific version rather than a range (i.e. SSMS plugins and apps with shared components running within a single appdomain). This switch will not change the current behaviour but will give us an opportunity to force specific versions if we wish.
=> Add switch to Update-NuspecDependenciesVersions to not use version ranges

Public/Invoke-NUnit3ForAssembly.ps1, Public/Invoke-NUnitForAssembly.ps1
This removes the validation set from the `-FrameworkVersion` parameters of both `Invoke-NUnitForAssembly` and `Invoke-NUnit3ForAssembly`
The caller gets to specify the version of NUnit they want to use. Different versions of NUnit support different frameworks, and are more than happy to complain if an unsupported framework version is specified. There's no need to apply our own validation, and it's actually got in the way a number of times recently.
=> Remove validation set from -FrameworkVersion parameters of the NUnit cmdlets

Public/Expand-ZipArchive.ps1, Public/New-ZipArchive.ps1
We have two alias declarations, neither of which are forced (use the `-Force`) switch, which makes reimporting the RedGate.Build module fail. Forcing those alias declarations helps to make importing this module idempotent.
=> Force our alias declarations

Public/Invoke-DotCoverForExecutable.ps1, Public/Invoke-NUnit3ForAssembly.ps1, RELEASENOTES.md, Tests/Nunit/3/Invoke-NUnit3ForAssembly.Tests.ps1
This adds the optional `-TargetWorkingDirectory` parameter to `Invoke-NUnit3ForAssembly` and `Invoke-DotCoverForExecutable` so that you can specify the working directory for the test run.
I've added three new unit tests to check that `Invoke-NUnit3ForAssembly` calls things in the expected way.
=> Set the working directory for a test run

Private/NUnit/3/Build-NUnit3CommandLineArguments.ps1, Tests/Nunit/3/Build-NUnit3CommandLineArguments.Tests.ps1
The `--err` argument has apparently not worked since nUnit Runner  2.9, and was removed altogether in 3.9.0, so we should remove it.
=> Remove dead argument

Private/Utils.ps1, Public/Remove-IgnoredTests.ps1, RELEASENOTES.md
This PR uses an xslt transform to remove ignored tests. The advantage of this is that it uses streams and avoids loading the whole contents of the file into memory. This can prevent out of memory exceptions with large test runs.
Additionally, some result files were observed during TeamCity runs to still be open after the test run had allegedly finished. The method now waits for the lock on the file to be released before
=> Use an xslt transform to remove ignored tests

Public/GitHub/Push-GitChangesToBranch.ps1
Looks like powershell 5.1.17763.1 (Windows Server 2019) is throwing errors even though `git checkout -B` is successful. Suspect that is because `git checkout -B` prints its output on stderr... 😓😓
=> Workaround powershell 5.1.17763.1 throwing errors on 'git checkout -B' 

Public/Invoke-NUnit3ForAssembly.ps1, Public/Invoke-NUnitForAssembly.ps1, RELEASENOTES.md
Tests that use LocalDB result in dotCover doing code coverage of sqlservr.exe - and consequently waiting for the LocalDB instance to exit before the code coverage is finished! Which normally takes 5-10 mins. In most situations, you only actually want to cover what's run by the tests themselves, and not external processes, so this PR defaults the process filter parameters in `Invoke-NUnitForAssembly` and `Invoke-NUnit3ForAssembly` to only include the NUnit process itself.
As this is a potentially breaking change, I've bumped the version number to 1.0.
As I've bumped the version number to 1.0, I thought it made sense to include another breaking change, of fixing the typo `-DotNotImportResultsToTeamcity` -> `-DoNotImportResultsToTeamcity` (which is only used in …
=> Only include NUnit process when running code coverage

Public/Invoke-NUnit3ForAssembly.ps1, Public/Invoke-NUnitForAssembly.ps1
Turns out my previous PR (#110) broke code coverage because it only included `nunit3-console.exe`, and not the agent process that actually runs the tests. So we got no code coverage. Only SQL Clone updated to RedGate.Build 1.0.0 so far, so I don't think this will have broken anyone else so far, thankfully!
=> Include all NUnit processes

Public/Rewrite-AssemblyInfo.ps1, Public/Rewrite-AssemblyInfos.ps1, Tests/Rewrite-AssemblyInfo.Tests.ps1, Tests/Rewrite-AssemblyInfos.Tests.ps1
This PR introduces the `Rewrite-AssemblyInfos` cmdlet, which rewrites all AssemblyInfo.cs files in a solution in a standard format. This was originally written for SQL Clone, but has had the SQL Clone specific code removed and tests added, and it should now be useful for other products.
=> Cmdlet to normalize AssemblyInfo.cs files

Private/NUnit/3/Build-NUnit3CommandLineArguments.ps1, Public/Invoke-NUnit3ForAssembly.ps1, Public/Rewrite-AssemblyInfo.ps1, RELEASENOTES.md, Tests/Nunit/3/Build-NUnit3CommandLineArguments.Tests.ps1, Tests/Rewrite-AssemblyInfo.Tests.ps1
This PR contains two completely independent things, they're in one PR because I needed them at the same time as so they form RedGate.Build 1.3.
The release notes diff is as good a description as I could write here!
=> Add -Timeout to Invoke-NUnit3ForAssembly, and preserve AssemblyTitle and CLSCompliant in Rewrite-AssemblyInfo

Private/ConvertTo-CSharpEscaped.ps1, Public/Rewrite-AssemblyInfo.ps1
- Escape C# strings correctly
- Tolerate input file not having a copyright year
=> Minor fixes to Rewrite-AssemblyInfo

Public/Rewrite-AssemblyInfo.ps1, Public/Rewrite-AssemblyInfos.ps1, RELEASENOTES.md, Tests/Rewrite-AssemblyInfo.Tests.ps1, Tests/Rewrite-AssemblyInfos.Tests.ps1, build.ps1
For semantically versioned assemblies, we want AssemblyVersion to just have a major version. So, I've introduced an `-AssemblyVersionMajorOnly` flag to `Rewrite-AssemblyInfos`.
=> Allow setting AssemblyVersion and AssemblyFileVersion differently
